name: CI/CD

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        user: action/checkout@3

      - name: Staring Node.js ${{matrix.node-version}}
        user: action/setup-node@3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install modules
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
