name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        user: actions/checkout@v4
      - name: Setup Node.js ${{matrix.node-version}}
        user: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
